# Site settings
title: A gulp.js generator for modern webapps
description: Scaffold out a front-end web app.
baseurl:
url: https://www.npmjs.com/package/generator-tapp

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: styles
